# Generated by Django 4.1.1 on 2022-11-08 13:41

import assignment.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', assignment.models.UserManager()),
            ],
        ),
    ]
